2020-02-02 09:14:12,429 ERROR 31919 nodejs.ClusterClientNoResponseError: client no response in 470734ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 31919
hostname: chupengfeideMacBook-Pro.local

2020-02-02 09:58:17,640 ERROR 37501 nodejs.ClusterClientNoResponseError: client no response in 86326ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 37501
hostname: chupengfeideMacBook-Pro.local

2020-02-02 10:17:58,337 ERROR 37501 nodejs.ClusterClientNoResponseError: client no response in 1020670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 37501
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:20:22,304 ERROR 41850 [-/::1/-/7ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find /index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 41850
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:22:25,175 ERROR 41883 [-/::1/-/3ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 41883
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:22:27,159 ERROR 41883 [-/::1/-/1ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 41883
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:22:51,089 ERROR 41928 [-/::1/-/3ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 41928
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:23:42,633 ERROR 41973 [-/::1/-/7ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 41973
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:24:47,933 ERROR 42026 [-/::1/-/7ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find ./view/index.ejs from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42026
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:24:49,373 ERROR 42026 [-/::1/-/0ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find ./view/index.ejs from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42026
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:29:47,578 ERROR 42146 [-/::1/-/8ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42146
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:30:31,740 ERROR 42160 [-/::1/-/8ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find ./index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42160
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:32:34,216 ERROR 42219 [-/::1/-/7ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42219
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:32:35,708 ERROR 42219 [-/::1/-/1ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42219
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:33:16,916 ERROR 42235 [-/::1/-/9ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42235
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:33:18,306 ERROR 42235 [-/::1/-/1ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42235
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:33:19,069 ERROR 42235 [-/::1/-/0ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42235
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:37:20,195 ERROR 42307 [-/::1/-/8ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find view/index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42307
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:43:57,200 ERROR 42459 [-/::1/-/8ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find view/index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42459
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:43:58,420 ERROR 42459 [-/::1/-/1ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find view/index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42459
hostname: chupengfeideMacBook-Pro.local

2020-02-02 11:46:43,080 ERROR 42565 [-/::1/-/8ms GET /news] nodejs.AssertionError [ERR_ASSERTION]: Can't find index from /Users/louis/Documents/dailyWork/node/egg-example/app/view
    at Map.resolve (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/view_manager.js:74:5)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 42565
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:06:50,712 ERROR 41927 nodejs.ClusterClientNoResponseError: client no response in 822918ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 41927
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:45:28,783 ERROR 43915 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43915
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:45:31,704 ERROR 43915 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43915
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:45:42,103 ERROR 43919 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43919
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:46:22,973 ERROR 43933 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43933
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:46:27,342 ERROR 43933 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43933
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:46:57,146 ERROR 43972 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43972
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:47:00,293 ERROR 43972 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43972
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:47:16,061 ERROR 43982 nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 43982
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:48:41,541 ERROR 44073 [-/127.0.0.1/-/10ms GET /] nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 44073
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:48:43,518 ERROR 44073 [-/127.0.0.1/-/1ms GET /] nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 44073
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:48:49,087 ERROR 44073 [-/127.0.0.1/-/1ms GET /] nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 44073
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:49:44,034 ERROR 44090 [-/127.0.0.1/-/12ms GET /] nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 44090
hostname: chupengfeideMacBook-Pro.local

2020-02-02 12:50:26,078 ERROR 44121 [-/127.0.0.1/-/12ms GET /] nodejs.SyntaxError: Missing catch or finally after try in /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:652:12)
    at Object.compile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:16)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)

pid: 44121
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:23:03,628 ERROR 45121 [-/127.0.0.1/-/8ms GET /] nodejs.ReferenceError: name is not defined
    at HomeController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/home.js:12:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 45121
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:23:05,379 ERROR 45121 [-/127.0.0.1/-/1ms GET /] nodejs.ReferenceError: name is not defined
    at HomeController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/home.js:12:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 45121
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:23:11,391 ERROR 45126 [-/127.0.0.1/-/12ms GET /] nodejs.TypeError: /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:14
    12|   <h2><%=api%></h2>
    13| 
 >> 14|   <h2><%=obj.name%></h2>
    15|   <ul>
    16|     <%for(var i = 0;i<list.length;i++) {%>
    17|       <li>

Cannot read property 'name' of undefined
    12|   <h2><%=api%></h2>
    13| 
 >> 14|   <h2><%=obj.name%></h2>
    15|   <ul>
    16|     <%for(var i = 0;i<list.length;i++) {%>
    17|       <li>

Cannot read property 'name' of undefined
    at eval (/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:15:29)
    at home (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)
    at ContextView.[contextView#render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
path: "/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html"
pid: 45126
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:23:38,594 ERROR 45126 [-/127.0.0.1/-/3ms GET /] nodejs.ReferenceError: /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:14
    12|   <h2><%=api%></h2>
    13| 
 >> 14|   <h2><%=obj[name]%></h2>
    15|   <ul>
    16|     <%for(var i = 0;i<list.length;i++) {%>
    17|       <li>

name is not defined
    12|   <h2><%=api%></h2>
    13| 
 >> 14|   <h2><%=obj[name]%></h2>
    15|   <ul>
    16|     <%for(var i = 0;i<list.length;i++) {%>
    17|       <li>

name is not defined
    at eval (/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:15:29)
    at home (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)
    at ContextView.[contextView#render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
path: "/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html"
pid: 45126
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:23:54,020 ERROR 45126 [-/127.0.0.1/-/2ms GET /] nodejs.TypeError: /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:14
    12|   <h2><%=api%></h2>
    13| 
 >> 14|   <h2><%=obj['name']%></h2>
    15|   <ul>
    16|     <%for(var i = 0;i<list.length;i++) {%>
    17|       <li>

Cannot read property 'name' of undefined
    12|   <h2><%=api%></h2>
    13| 
 >> 14|   <h2><%=obj['name']%></h2>
    15|   <ul>
    16|     <%for(var i = 0;i<list.length;i++) {%>
    17|       <li>

Cannot read property 'name' of undefined
    at eval (/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:15:28)
    at home (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)
    at ContextView.[contextView#render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
path: "/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html"
pid: 45126
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:24:53,049 ERROR 45203 [-/127.0.0.1/-/7ms GET /] nodejs.TypeError: Cannot read property 'name' of undefined
    at HomeController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/home.js:11:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 45203
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:25:59,464 ERROR 45265 [-/127.0.0.1/-/6ms GET /] nodejs.TypeError: Cannot read property 'name' of undefined
    at HomeController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/home.js:11:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 45265
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:26:38,166 ERROR 45299 [-/127.0.0.1/-/7ms GET /] nodejs.TypeError: Cannot read property 'name' of undefined
    at HomeController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/home.js:11:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 45299
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:27:05,008 ERROR 45299 [-/127.0.0.1/-/1ms GET /] nodejs.TypeError: Cannot read property 'name' of undefined
    at HomeController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/home.js:11:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

pid: 45299
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:28:28,348 ERROR 45384 [-/127.0.0.1/-/12ms GET /] nodejs.ReferenceError: /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:13
    11| <body>
    12|   <h2><%=api%></h2>
 >> 13|   <h2><%=name%></h2>
    14|   <ul>
    15|     <%for(var i = 0;i<list.length;i++) {%>
    16|       <li>

name is not defined
    11| <body>
    12|   <h2><%=api%></h2>
 >> 13|   <h2><%=name%></h2>
    14|   <ul>
    15|     <%for(var i = 0;i<list.length;i++) {%>
    16|       <li>

name is not defined
    at eval (/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:15:25)
    at home (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)
    at ContextView.[contextView#render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
path: "/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html"
pid: 45384
hostname: chupengfeideMacBook-Pro.local

2020-02-02 13:29:07,199 ERROR 45420 [-/127.0.0.1/-/14ms GET /] nodejs.ReferenceError: /Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:13
    11| <body>
    12|   <h2><%=api%></h2>
 >> 13|   <h2><%=name%></h2>
    14|   <ul>
    15|     <%for(var i = 0;i<list.length;i++) {%>
    16|       <li>

name is not defined
    11| <body>
    12|   <h2><%=api%></h2>
 >> 13|   <h2><%=name%></h2>
    14|   <ul>
    15|     <%for(var i = 0;i<list.length;i++) {%>
    16|       <li>

name is not defined
    at eval (/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html:15:25)
    at home (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/ejs/lib/ejs.js:485:10)
    at Promise (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:16:11)
    at new Promise (<anonymous>)
    at EjsView.[EjsView#_render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:15:12)
    at EjsView.render (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view-ejs/lib/view.js:28:36)
    at ContextView.[contextView#render] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-view/lib/context_view.js:70:23)
    at <anonymous>
path: "/Users/louis/Documents/dailyWork/node/egg-example/app/view/home.html"
pid: 45420
hostname: chupengfeideMacBook-Pro.local

2020-02-02 14:00:55,231 ERROR 43372 nodejs.ClusterClientNoResponseError: client no response in 918412ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 43372
hostname: chupengfeideMacBook-Pro.local

2020-02-02 14:19:15,008 ERROR 43372 nodejs.ClusterClientNoResponseError: client no response in 959758ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 43372
hostname: chupengfeideMacBook-Pro.local

2020-02-02 16:19:21,537 ERROR 43372 nodejs.ClusterClientNoResponseError: client no response in 7206525ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 43372
hostname: chupengfeideMacBook-Pro.local

2020-02-02 18:19:07,980 ERROR 43372 nodejs.ClusterClientNoResponseError: client no response in 7186272ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 43372
hostname: chupengfeideMacBook-Pro.local

2020-05-03 09:39:49,067 ERROR 50395 nodejs.MongoNetworkError: failed to connect to server [host:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND host host:27017]
    at Pool.<anonymous> (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:198:13)
    at createConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:561:14)
    at connect (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.err (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
name: "MongoNetworkError"
pid: 50395
hostname: chupengfeideMacBook-Pro.local

2020-05-03 09:39:49,074 ERROR 50395 [-/127.0.0.1/-/0ms GET /] nodejs.MongoNetworkError: failed to connect to server [host:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND host host:27017]
    at Pool.<anonymous> (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:198:13)
    at createConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:561:14)
    at connect (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.err (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
name: "MongoNetworkError"
pid: 50395
hostname: chupengfeideMacBook-Pro.local

2020-05-03 09:39:50,228 ERROR 50399 nodejs.MongoNetworkError: failed to connect to server [host:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND host host:27017]
    at Pool.<anonymous> (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:198:13)
    at createConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:561:14)
    at connect (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.err (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
name: "MongoNetworkError"
pid: 50399
hostname: chupengfeideMacBook-Pro.local

2020-05-03 09:39:50,239 ERROR 50399 [-/127.0.0.1/-/0ms GET /] nodejs.MongoNetworkError: failed to connect to server [host:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND host host:27017]
    at Pool.<anonymous> (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:198:13)
    at createConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:561:14)
    at connect (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/pool.js:994:11)
    at makeConnection (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:31:7)
    at callback (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.err (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
name: "MongoNetworkError"
pid: 50399
hostname: chupengfeideMacBook-Pro.local

2020-05-03 17:57:46,109 ERROR 56074 [-/127.0.0.1/-/8ms GET /mongo] nodejs.TypeError: Cannot read property '_id' of undefined
    at docs.map.doc (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:208:45)
    at Array.map (<anonymous>)
    at prepareDocs (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:207:15)
    at insertDocuments (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:256:10)
    at InsertOneOperation.execute (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/collection.js:516:10)
    at MongoDB.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/@brickyang/easy-mongodb/lib/mongo.js:126:37)
    at MongodbModelController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/mongodbModel.js:24:37)
    at Object.callFn (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)

pid: 56074
hostname: chupengfeideMacBook-Pro.local

2020-05-03 17:58:12,673 ERROR 56092 [-/127.0.0.1/-/8ms GET /mongo] nodejs.TypeError: Cannot read property '_id' of undefined
    at docs.map.doc (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:208:45)
    at Array.map (<anonymous>)
    at prepareDocs (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:207:15)
    at insertDocuments (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:256:10)
    at InsertOneOperation.execute (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/collection.js:516:10)
    at MongoDB.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/@brickyang/easy-mongodb/lib/mongo.js:126:37)
    at MongodbModelController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/mongodbModel.js:24:37)
    at Object.callFn (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)

pid: 56092
hostname: chupengfeideMacBook-Pro.local

2020-05-03 17:58:31,211 ERROR 56106 [-/127.0.0.1/-/8ms GET /mongo] nodejs.TypeError: Cannot read property '_id' of undefined
    at docs.map.doc (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:208:45)
    at Array.map (<anonymous>)
    at prepareDocs (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:207:15)
    at insertDocuments (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:256:10)
    at InsertOneOperation.execute (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/collection.js:516:10)
    at MongoDB.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/@brickyang/easy-mongodb/lib/mongo.js:126:37)
    at MongodbModelController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/mongodbModel.js:24:37)
    at Object.callFn (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)

pid: 56106
hostname: chupengfeideMacBook-Pro.local

2020-05-03 17:58:48,611 ERROR 56117 [-/127.0.0.1/-/8ms GET /mongo] nodejs.TypeError: Cannot read property '_id' of undefined
    at docs.map.doc (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:208:45)
    at Array.map (<anonymous>)
    at prepareDocs (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:207:15)
    at insertDocuments (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:256:10)
    at InsertOneOperation.execute (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/collection.js:516:10)
    at MongoDB.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/@brickyang/easy-mongodb/lib/mongo.js:126:37)
    at MongodbModelController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/mongodbModel.js:24:37)
    at Object.callFn (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)

pid: 56117
hostname: chupengfeideMacBook-Pro.local

2020-05-03 18:11:15,548 ERROR 56359 [-/127.0.0.1/-/7ms GET /mongo] nodejs.TypeError: Cannot read property '_id' of undefined
    at docs.map.doc (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:208:45)
    at Array.map (<anonymous>)
    at prepareDocs (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:207:15)
    at insertDocuments (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/common_functions.js:256:10)
    at InsertOneOperation.execute (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/insert_one.js:26:5)
    at executeOperation (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
    at Collection.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/mongodb/lib/collection.js:516:10)
    at MongoDB.insertOne (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/@brickyang/easy-mongodb/lib/mongo.js:126:37)
    at MongodbModelController.index (/Users/louis/Documents/dailyWork/node/egg-example/app/controller/mongodbModel.js:24:43)
    at Object.callFn (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)

pid: 56359
hostname: chupengfeideMacBook-Pro.local

2020-05-03 23:30:13,486 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 941885ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-03 23:46:01,835 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 928047ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 00:01:47,083 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924807ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 00:17:31,868 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924332ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 00:33:17,839 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 925636ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 00:49:01,701 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923576ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 01:04:46,868 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924636ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 01:20:30,845 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923664ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 01:36:15,881 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924572ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 01:52:00,893 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924878ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 02:07:44,906 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923638ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 02:23:28,868 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923594ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 02:39:11,883 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 922874ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 02:54:56,869 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924703ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 03:10:40,885 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923557ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 03:26:25,857 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924792ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 03:42:10,854 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924676ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 03:57:55,828 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924531ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 04:13:39,847 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923717ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 04:29:23,840 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923726ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 04:45:07,841 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 923619ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 05:00:52,820 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 924898ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 05:14:16,892 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 783760ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 05:30:09,962 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 920107ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 05:45:50,388 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 920406ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 06:01:31,006 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 920610ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 06:17:10,732 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 919710ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 06:27:50,656 ERROR 47579 nodejs.ClusterClientNoResponseError: client no response in 619913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47579
hostname: chupengfeideMacBook-Pro.local

2020-05-04 15:52:09,564 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 604788ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-04 16:08:04,045 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 914467ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-04 18:08:34,355 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 7210302ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-04 20:42:19,981 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 9159097ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-04 22:42:25,675 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 7205050ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 00:42:30,860 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 7204641ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 01:53:21,701 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 4250721ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 03:43:02,561 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 6560496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 07:07:57,049 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 12274447ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 07:25:40,201 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 423078ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 07:52:12,887 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 332528ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 08:00:34,238 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 301337ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 08:35:33,780 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 1599481ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 08:47:01,827 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 227979ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2020-05-05 08:56:56,210 ERROR 62385 nodejs.ClusterClientNoResponseError: client no response in 226048ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/louis/Documents/dailyWork/node/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 62385
hostname: chupengfeideMacBook-Pro.local

2022-08-06 20:25:06,326 ERROR 66028 nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (node:events:526:28)
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
name: "MongoNetworkError"
pid: 66028
hostname: chupengfeideMacBook-Pro.local

2022-08-06 20:25:06,329 ERROR 66028 [-/127.0.0.1/-/1ms GET /] nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (node:events:526:28)
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
name: "MongoNetworkError"
pid: 66028
hostname: chupengfeideMacBook-Pro.local

2022-08-07 10:19:57,753 ERROR 69859 nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (node:events:526:28)
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
name: "MongoNetworkError"
pid: 69859
hostname: chupengfeideMacBook-Pro.local

2022-08-07 10:19:57,755 ERROR 69859 [-/127.0.0.1/-/1ms GET /] nodejs.MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (node:events:526:28)
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/Users/louis/Documents/myProject/cdp-wpm-cli-node/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
name: "MongoNetworkError"
pid: 69859
hostname: chupengfeideMacBook-Pro.local

